/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ComponentSpaceImport } from './routes/component/space'
import { Route as ComponentCalendarImport } from './routes/component/calendar'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ComponentSpaceRoute = ComponentSpaceImport.update({
  id: '/component/space',
  path: '/component/space',
  getParentRoute: () => rootRoute,
} as any)

const ComponentCalendarRoute = ComponentCalendarImport.update({
  id: '/component/calendar',
  path: '/component/calendar',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/component/calendar': {
      id: '/component/calendar'
      path: '/component/calendar'
      fullPath: '/component/calendar'
      preLoaderRoute: typeof ComponentCalendarImport
      parentRoute: typeof rootRoute
    }
    '/component/space': {
      id: '/component/space'
      path: '/component/space'
      fullPath: '/component/space'
      preLoaderRoute: typeof ComponentSpaceImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/component/calendar': typeof ComponentCalendarRoute
  '/component/space': typeof ComponentSpaceRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/component/calendar': typeof ComponentCalendarRoute
  '/component/space': typeof ComponentSpaceRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/component/calendar': typeof ComponentCalendarRoute
  '/component/space': typeof ComponentSpaceRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/component/calendar' | '/component/space'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/component/calendar' | '/component/space'
  id: '__root__' | '/' | '/component/calendar' | '/component/space'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ComponentCalendarRoute: typeof ComponentCalendarRoute
  ComponentSpaceRoute: typeof ComponentSpaceRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ComponentCalendarRoute: ComponentCalendarRoute,
  ComponentSpaceRoute: ComponentSpaceRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/component/calendar",
        "/component/space"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/component/calendar": {
      "filePath": "component/calendar.tsx"
    },
    "/component/space": {
      "filePath": "component/space.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
