/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ComponentMessageImport } from './routes/component/message'
import { Route as ComponentCalendarImport } from './routes/component/calendar'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ComponentMessageRoute = ComponentMessageImport.update({
  id: '/component/message',
  path: '/component/message',
  getParentRoute: () => rootRoute,
} as any)

const ComponentCalendarRoute = ComponentCalendarImport.update({
  id: '/component/calendar',
  path: '/component/calendar',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/component/calendar': {
      id: '/component/calendar'
      path: '/component/calendar'
      fullPath: '/component/calendar'
      preLoaderRoute: typeof ComponentCalendarImport
      parentRoute: typeof rootRoute
    }
    '/component/message': {
      id: '/component/message'
      path: '/component/message'
      fullPath: '/component/message'
      preLoaderRoute: typeof ComponentMessageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/component/calendar': typeof ComponentCalendarRoute
  '/component/message': typeof ComponentMessageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/component/calendar': typeof ComponentCalendarRoute
  '/component/message': typeof ComponentMessageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/component/calendar': typeof ComponentCalendarRoute
  '/component/message': typeof ComponentMessageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/component/calendar' | '/component/message'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/component/calendar' | '/component/message'
  id: '__root__' | '/' | '/component/calendar' | '/component/message'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ComponentCalendarRoute: typeof ComponentCalendarRoute
  ComponentMessageRoute: typeof ComponentMessageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ComponentCalendarRoute: ComponentCalendarRoute,
  ComponentMessageRoute: ComponentMessageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/component/calendar",
        "/component/message"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/component/calendar": {
      "filePath": "component/calendar.tsx"
    },
    "/component/message": {
      "filePath": "component/message.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
